openapi: 3.0.1
info:
  title: Application API
  description: |
    API providing title information to prepare an application to change the register.

    NOTE: this API definition assumes that **the user is a conveyancer** acting on behalf of an applicant to change the register
  version: 0.0.1
servers:
- url: /
paths:
  /applications/draft:
    post:
      description: Draft a new application and optionally create a new notification
        topic for the title
      operationId: applications_draft_post
      requestBody:
        description: Details of the application to draft.
        content:
          application/json:
            schema:
              type: array
              items:
                discriminator:
                  propertyName: application_type
                  mapping:
                    transfer_of_whole: '#/components/schemas/TransferRequest'
                    creation_of_new_charge: '#/components/schemas/ChargeRequest'
                anyOf:
                - $ref: '#/components/schemas/TransferRequest'
                - $ref: '#/components/schemas/ChargeRequest'
        required: true
      responses:
        "200":
          description: The drafted application passed validation. A topic for the
            title already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationSuccessResponse'
        "201":
          description: The drafted application passed validation. A topic was created
            for the title.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
        "400":
          description: The drafted application failed validation. A topic was created
            or already exists for the title.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        "404":
          description: An invalid title number was supplied.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /applications/validate:
    put:
      description: Validate an application before submission.
      operationId: applications_validate_put
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                discriminator:
                  propertyName: application_type
                  mapping:
                    transfer_of_whole: '#/components/schemas/TransferRequest'
                    creation_of_new_charge: '#/components/schemas/ChargeRequest'
                anyOf:
                - $ref: '#/components/schemas/TransferRequest'
                - $ref: '#/components/schemas/ChargeRequest'
        required: true
      responses:
        "200":
          description: Confirmation that the application passed HMLR vaildation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationSuccessResponse'
        "400":
          description: A summary of the outstanding assurances required for an application.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /applications/submit:
    post:
      description: Validate and submit an application to change the register
      operationId: applications_submit_post
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                discriminator:
                  propertyName: application_type
                  mapping:
                    transfer_of_whole: '#/components/schemas/TransferRequest'
                    creation_of_new_charge: '#/components/schemas/ChargeRequest'
                anyOf:
                - $ref: '#/components/schemas/TransferRequest'
                - $ref: '#/components/schemas/ChargeRequest'
        required: true
      responses:
        "202":
          description: Confirmation that the application passed HMLR validation and
            has been accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitApplicationResponse'
        "400":
          description: A summary of the outstanding assurances required for an application.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Address:
      required:
      - description
      - legacy_addr_id
      type: object
      properties:
        description:
          type: string
          description: Full description of the address with its constituent parts
            combined.
          example: 123 Smith Street, Plymouth (PL1 2AB)
        type:
          type: string
          description: The type of address.
          enum:
          - uk
          - foreign
          - bfpo
          - dx
          - electronic
          - unknown
        legacy_addr_id:
          type: string
          description: The legacy identifier for the address.
          example: 2019-11-18 12.52.12.555232
      description: Represents an address on the register. This may be from an A1 entry
        or a schedule.
      example:
        description: 123 Smith Street, Plymouth (PL1 2AB)
        legacy_addr_id: 2019-11-18 12.52.12.555232
        type: uk
    ApplicationReference:
      type: string
      description: |
        The Application Barcode Reference (ABR) of the latest application to make a substantive change to the register
        for this title.
      example: BADD31A
    ApplicationRequest:
      required:
      - title_number
      type: object
      properties:
        title_number:
          $ref: '#/components/schemas/TitleNumber'
      description: The base values required for an application request
    ApplicationRequestResponse:
      required:
      - application_type
      - validation_issues
      - validation_successes
      type: object
      properties:
        application_type:
          type: string
          enum:
          - transfer_of_whole
          - creation_of_new_charge
        validation_issues:
          type: array
          items:
            $ref: '#/components/schemas/ValidationIssue'
        validation_successes:
          type: array
          items:
            $ref: '#/components/schemas/ValidationSuccess'
      example:
        application_type: transfer_of_whole
        validation_successes:
        - value: AGL117262
          property_name: title_number
        - value: AGL117262
          property_name: title_number
        validation_issues:
        - issue_code: issue_code
          message: A title does not exist for the given title number
          value: AGL117262
          property_name: title_number
        - issue_code: issue_code
          message: A title does not exist for the given title number
          value: AGL117262
          property_name: title_number
    AssuranceOfDeath:
      type: boolean
      description: By providing this field, you are assuring the death of the named
        proprietor. **NOTE - This field only be provided by conveyancers**
    ChargeRequest:
      required:
      - application_type
      type: object
      properties:
        application_type:
          type: string
          enum:
          - creation_of_new_charge
        borrowers:
          type: array
          items:
            $ref: '#/components/schemas/Proprietor'
        lender:
          $ref: '#/components/schemas/Organisation'
        title_guarantee:
          $ref: '#/components/schemas/ChargeRequest_title_guarantee'
        additional_provisions:
          type: array
          items:
            oneOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
            - type: object
      allOf:
      - $ref: '#/components/schemas/ApplicationRequest'
    ClassOfTitle:
      type: string
      description: |-
        The *class of title* is a measure of confidence that HM Land Registry has in guaranteeing the proprietor(s) of the
        title against a legal challenge to that title.


        ---

        A property of this type may be any of the following values:
        - `absolute`: A *title absolute* is conferred to the proprietor(s) if it is determined that the claim to proprietorship is
          indisputable.
          When a title is first registered, it is required to provide a complete history of ownership for the 15 years prior
          to registration.
          In the case of a leasehold title, it is also required to prove that the landlord has the rights to grant a lease -
          either through demonstrating 15 years of ownership history, or through an official copy of the register if the
          freehold is already registered.
          Most titles are considered to be titles absolute.

        - `good`: A *good leasehold* title is conferred to the proprietor(s) if the claim to the leasehold title is satisfactory,
          but the landlord's claim to the freehold title cannot be verified.
          In such a situation, it is unknown whether the claimed landlord has the power to grant such a lease, or whether
          any covenants or restrictions affect the property.

        - `qualified`: A *qualified title* is conferred to the proprietor(s) if the claim to proprietorship is incomplete.
          Such a class of title would be granted if, when first registered, did not fully account for the 15 years prior to
          registration.
          A qualified title is susceptible to being challenged by a person with a stronger claim to the title.

        - `possessory`: A *possessory title* is conferred to the proprietor(s) when proprietorship is claimed by right of adverse
          possession or when no documentation can be provided asserting the title.
      example: absolute
      enum:
      - absolute
      - good
      - qualified
      - possessory
    CommonholdType:
      type: string
      description: |
        A lookup value which indicates whether the current status of a Title which is registered as
        commonhold is that of a ‘common parts title’ or ‘common unit title’.
      example: part
      enum:
      - part
      - unit
    DeclarationOfTrust:
      required:
      - trust_type
      type: object
      properties:
        trust_type:
          type: string
          description: The type of trust
          enum:
          - joint_tenants
          - tenants_in_common_in_equal_shares
          - held_on_trust
        trust_details:
          type: string
          description: The details of the trust or of the trust instrument. Only required
            if trust_type is 'held_on_trust'
      description: Where the transferee is more than one person, provide a declaration
        of trust
    EstateInterest:
      type: string
      description: |-
        Describes the type of *legal interest* (the collection of rights) of an *estate* (the land to which these rights
        apply).


        ---

        A property of this type may be any of the following values:
        - `estate_in_land`: An *estate_in_land* refers to ownership or possessory rights to land or property.

          A freehold title or a leasehold title would be an example of an estate_in_land.

        - `affecting franchise`: A *franchise* is a right granted by the Crown through a charter or letters patent, such as the right to host a
          market or a fair.
          A title to franchise does not grant any ownership to the land in question; it is distinct from freehold or
          leasehold titles.

          A franchise is an *affecting franchise* if it is registered to a defined extent of land and is capable of
          affecting the title to an estate.
          Otherwise, the franchise is a *relating franchise*.

        - `relating franchise`: A *franchise* is a right granted by the Crown through a charter or letters patent, such as the right to host a
          market or a fair.
          A title to franchise does not grant any ownership to the land in question; it is distinct from freehold or
          leasehold titles.

          A franchise is an *affecting franchise* if it is registered to a defined extent of land and is capable of
          affecting the title to an estate.
          Otherwise, the franchise is a *relating franchise*.

        - `manor`: A *manor* was, historically, central to feudalism - either the Crown or a superior lord would grant ownership and
          other rights in exchange for their allegiance and service.

          From a modern perspective, there are three main elements:
          - The *lordship*, the owner of which is entitled to refer to themself as the lord of that manor
          - The *manorial*, which refers to the land and the manor house upon it
          - The *seignory*, which refers to additional rights on the land which have been reserved by the lord, such as
            hunting or fishing rights

        - `profit à prendre in gross`: A *profit à prendre in gross* is the right to take a natural resource from another person's land.
          The owner of the profit may exercise that right irrespective of the ownership of the land in question.
          The profit also effectively grants an easement on the land due to the necessity of physically accessing the
          resource in order to take it.

        - `rentcharge`: A *rentcharge* is a regular payment made between the owner of a freehold title and another person who otherwise
          has no additional interest in the land.
          This distinguishes a rentcharge from ground rent (which is only applicable to leasehold titles) or from a charge
          (which is the use of a title as collateral in order to protect a lender in the event that a borrower defaults on
          their repayments).

          A rentcharge is *terminable* if it is only applicable for a fixed term; otherwise, it is *perpetual*.

        - `perpetual rentcharge`: A *rentcharge* is a regular payment made between the owner of a freehold title and another person who otherwise
          has no additional interest in the land.
          This distinguishes a rentcharge from ground rent (which is only applicable to leasehold titles) or from a charge
          (which is the use of a title as collateral in order to protect a lender in the event that a borrower defaults on
          their repayments).

          A rentcharge is *terminable* if it is only applicable for a fixed term; otherwise, it is *perpetual*.

        - `terminable rentcharge`: A *rentcharge* is a regular payment made between the owner of a freehold title and another person who otherwise
          has no additional interest in the land.
          This distinguishes a rentcharge from ground rent (which is only applicable to leasehold titles) or from a charge
          (which is the use of a title as collateral in order to protect a lender in the event that a borrower defaults on
          their repayments).

          A rentcharge is *terminable* if it is only applicable for a fixed term; otherwise, it is *perpetual*.
      example: estate_in_land
      enum:
      - estate_in_land
    Execution:
      type: boolean
      description: Assurance that the deed has been executed
    Language:
      type: string
      description: |
        A three-character code representing a language according to the
        [ISO 639-3 standard](https://iso639-3.sil.org/code_tables/639/data).
      example: eng
      enum:
      - eng
      - cym
    NoticeOfDeath:
      required:
      - assurance_of_death
      - deceased
      type: object
      properties:
        deceased:
          $ref: '#/components/schemas/PrivateIndividual'
        assurance_of_death:
          $ref: '#/components/schemas/AssuranceOfDeath'
    Organisation:
      required:
      - name
      - organisation_type
      - proprietor_type
      properties:
        proprietor_type:
          type: string
          description: Coarse classification of a proprietor. Used to easily distinguish
            between a private individual and an organisation.
          enum:
          - organisation
        organisation_type:
          type: string
          description: Fine-grained classification of an organisation
          enum:
          - county_council
          - limited_company_or_public_limited_company
          - limited_liability_partnership
          - local_authority
        sequence:
          minimum: 1
          type: integer
          description: The position of the proprietor within the register.
          format: int32
          example: 2
        name:
          type: string
          description: Name of the organisation. If it's a charity, the charity name
            will appear here.
          example: Acme inc.
        company_registration_number:
          type: string
          description: |
            Number which is a unique identifier assigned to a company when it is registered at companies house.
            Although the name of the company may change, the company registration number will remain the same.
          example: "09579244"
        location:
          type: string
          enum:
          - england_or_wales
          - scotland
          - northern_ireland
          - overseas
        legacy_name_id:
          type: string
          example: 2019-11-18 12.52.12.555232
        addresses:
          type: array
          description: |
            A list of addresses relating to the proprietor.
            May be the same address as other proprietors present on the title.
          items:
            $ref: '#/components/schemas/ProprietorAddress'
    PrivateIndividual:
      required:
      - name
      - proprietor_type
      - sequence
      properties:
        proprietor_type:
          type: string
          description: Coarse classification of a proprietor. Used to easily distinguish
            between a private individual and an organisation.
          enum:
          - private_individual
        sequence:
          minimum: 1
          type: integer
          description: The position of the proprietor in the register.
          format: int32
          example: 1
        name:
          type: string
          description: Full name of the private individual.
          example: Mrs Sarah Louise Smith OBE
        title:
          type: string
          example: Mrs
        fore_names:
          type: string
          example: Sarah Louise
        surname:
          type: string
          example: Smith
        decor:
          type: string
          description: Text which contains the details of any decoration and/or title
            held by a private individual. e.g. 'OBE','GC', 'KCMG'. For those private
            individuals holding titles such as 'Duke of ...', 'Lord' etc., the particulars
            of such titles will be held in this field.
          example: OBE
        legacy_name_id:
          type: string
          example: 2019-11-18 12.52.12.555232
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/ProprietorAddress'
    Property:
      type: object
      properties:
        sequence:
          minimum: 1
          type: integer
          description: |
            The position of the property within the register.
            The first property is usually from the first entry on the Property register (A1)
            but could come from a schedule.
          format: int32
          example: 1
        address:
          $ref: '#/components/schemas/Address'
      description: Represents a property on the title.
      example:
        sequence: 1
        address:
          description: 123 Smith Street, Plymouth (PL1 2AB)
          legacy_addr_id: 2019-11-18 12.52.12.555232
          type: uk
    Proprietor:
      properties:
        proprietor_type:
          type: string
      example:
        proprietor_type: proprietor_type
      discriminator:
        propertyName: proprietor_type
        mapping:
          private_individual: '#/components/schemas/PrivateIndividual'
          organisation: '#/components/schemas/Organisation'
      oneOf:
      - $ref: '#/components/schemas/PrivateIndividual'
      - $ref: '#/components/schemas/Organisation'
    ProprietorAddress:
      required:
      - description
      - legacy_addr_id
      type: object
      properties:
        description:
          type: string
          description: Full description of the property with its constituent parts
            combined.
          example: 123 Smith Street, Plymouth (PL1 2AB)
        type:
          type: string
          description: The type of address.
          enum:
          - uk
          - foreign
          - bfpo
          - dx
          - electronic
          - unknown
        care_of_name:
          type: string
          description: |
            Name of person, persons or organisation. Used in connection with an address which is 'care of', 'poste restante' or 'accomodation address'.
          example: Hammonds Direct
        care_of_indicator:
          type: boolean
          description: |
            Indicates whether or not an address is a 'care of', 'poste restante' or 'accomodation address'.
            The address doesn't have to have a care_of_name if this is true.
          example: true
        sequence:
          minimum: 1
          type: integer
          description: The position of the address within the context of a single
            proprietor.
          format: int32
          example: 1
        legacy_addr_id:
          type: string
          description: The legacy identifier for the address.
          example: 2019-11-18 12.52.12.555232
      description: Represents the address of a proprietor.
    RegisterEntry:
      required:
      - entry_date
      - language_code
      - legacy_entry_id
      type: object
      properties:
        sub_register_code:
          $ref: '#/components/schemas/SubRegister'
        sub_register_sequence:
          minimum: 1
          type: integer
          description: The position of the entry within its sub register (or schedule,
            if specified).
          format: int32
          example: 1
        schedule:
          $ref: '#/components/schemas/ScheduleInfo'
        entry_sequence:
          minimum: 1
          type: integer
          description: The position of the entry within the entire register.
          format: int32
          example: 1
        role_code:
          maxLength: 4
          minLength: 4
          pattern: ^[A-Z]{4}$
          type: string
          description: A four-character code that identifies the role that an entry
            fulfills within the register.
          example: OJPR
        entry_date:
          type: string
          description: The date on which the entry was added to the register.
          format: date
        language_code:
          $ref: '#/components/schemas/Language'
        draft_entry_version:
          minimum: 1
          type: integer
          description: The version number of the entry template used to create this
            entry.
          format: int32
          example: 1
        draft_entry_code:
          maxLength: 5
          minLength: 5
          pattern: ^[A-Z]{2,5}[0-9]*$
          type: string
          description: |
            Identifies the *computerised register entry* (CRE) or *computerised search entry* (CSE) that this entry has used
            as an entry template.
          example: BX900
        legacy_entry_id:
          type: string
          description: |
            The unique identifier for this entry as used by the legacy database.
          example: '{}'
        priority_timestamp:
          type: string
          description: |
            The timestamp representing the date and time that the associated application was entered onto the daylist.
          format: date-time
        entry_text:
          type: string
          description: Full entry text as shown on the register.
          example: No disposition by a sole proprietor of the registered estate (except
            a trust corporation) under which capital money arises is to be registered
            unless authorised by an order of the court.
          x-data-quality:
          - tag: data_quality_no_entry_text
            message: The entry text is currently unavailable.
      description: |
        Represents an entry on the register for a title.
      example:
        schedule:
          sequence: 1
          code: l
          header:
            eng: Schedule of rentcharges
            cym: Atodlen rhent-daliadau cofrestredig
        language_code: eng
        entry_text: No disposition by a sole proprietor of the registered estate (except
          a trust corporation) under which capital money arises is to be registered
          unless authorised by an order of the court.
        legacy_entry_id: '{}'
        sub_register_sequence: 1
        draft_entry_code: BX900
        role_code: OJPR
        priority_timestamp: 2000-01-23T04:56:07.000+00:00
        entry_sequence: 1
        draft_entry_version: 1
        sub_register_code: a
        entry_date: 2000-01-23
    ScheduleCode:
      type: string
      description: |
        A single-character code that identifies the schedule.
        A schedule is an entry in the register that conforms to a particular structure.

        The schedule code may be any of the following values:
        - `d`: the entry is part of the schedule of deeds imposing restrictive covenants
        - `f`: the entry is part of the schedule of leases of easements
        - `h`: the entry is part of the schedule of a single registered lease
        - `l`: the entry is part of the schedule of notices of lease
        - `m`: the entry is part of the schedule of registered leases
        - `p`: the entry is part of the schedule of properties
        - `q`: the entry is part of the schedule of a single registered lease, charged by a registered rentcharge
        - `r`: the entry is part of the schedule of registered rentcharges
        - `s`: the entry is part of the schedule of restrictive covenants
        - `t`: the entry is part of the schedule of apportioned rent
        - `w`: the entry is part of the schedule of rentcharges
        - `x`: the entry is part of the schedule of personal covenants
        - `y`: the entry is part of the schedule of apportionments and exonerating rentcharges
        - `z`: the entry is part of the schedule of rentcharges created on transfer of part
      example: l
      enum:
      - d
      - f
      - h
      - l
      - m
      - p
      - q
      - r
      - s
      - t
      - w
      - x
      - "y"
      - z
    ScheduleInfo:
      required:
      - code
      - header
      - sequence
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ScheduleCode'
        sequence:
          minimum: 1
          type: integer
          description: The position of the entry within its schedule.
          format: int32
          example: 1
        header:
          type: object
          additionalProperties:
            type: string
          description: The official header text of this schedule.
          example:
            eng: Schedule of rentcharges
            cym: Atodlen rhent-daliadau cofrestredig
      description: |
        Encapsulates information about a schedule entry.
      example:
        sequence: 1
        code: l
        header:
          eng: Schedule of rentcharges
          cym: Atodlen rhent-daliadau cofrestredig
    SubmitApplicationResponse:
      required:
      - application_reference
      type: object
      properties:
        application_reference:
          $ref: '#/components/schemas/ApplicationReference'
      example:
        application_reference: BADD31A
      allOf:
      - $ref: '#/components/schemas/ValidationSuccessResponse'
    SubRegister:
      type: string
      description: |
        A single-character code that identifies in which part of the register an entry resides.

        The subregister code may be any of the following values:
        - `a`: the entry is part of the property register
        - `b`: the entry is part of the proprietorship register
        - `c`: the entry is part of the charges register
      example: a
      enum:
      - a
      - b
      - c
    Tenure:
      type: string
      description: |-
        The tenure of a title determines the rights of that title's proprietor(s).

        Currently, the law in England and Wales permits two kinds of interest: *freehold* and *leasehold*.


        ---

        A property of this type may be any of the following values:
        - `freehold`: Indicates that this is a freehold title; i.e. that full, perpetual, ownership rights of the specified property and
          land are granted to the proprietor(s).

        - `leasehold`: Indicates that this is a leasehold title; i.e. that possessory rights of the property (but not the land) have been
          granted to the proprietor(s) for the duration of the lease agreement with the freeholder(s).
      example: freehold
      enum:
      - freehold
      - leasehold
    Title:
      required:
      - application_reference
      - caution_against_first_registration
      - entries
      - pending_applications
      - properties
      - proprietors
      - status
      - title_number
      type: object
      properties:
        title_number:
          $ref: '#/components/schemas/TitleNumber'
        tenure:
          $ref: '#/components/schemas/Tenure'
        class_of_title:
          $ref: '#/components/schemas/ClassOfTitle'
        status:
          $ref: '#/components/schemas/TitleStatusInfo'
        edition_date:
          type: string
          description: |
            The date on which the current version of the register was published.
          format: date
        pending_applications:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationReference'
        application_reference:
          $ref: '#/components/schemas/ApplicationReference'
        application_timestamp:
          type: string
          description: |
            The date and time that the latest application to make a substantive change to the register for this title was submitted.
          format: date-time
        welsh:
          type: boolean
          description: |
            Indicates that the title falls under the Welsh administration area.
          example: false
        caution_against_first_registration:
          type: boolean
          description: |
            Boolean value stating whether this title is a caution against first registration. Cautions against dealings are excluded since they are purely an application data item.
          example: true
        continuation_title_number:
          maxLength: 9
          type: string
          description: |
            Title number under which a closed title has been continued.
          example: AGL117262
        previous_title_number:
          maxLength: 9
          type: string
          description: |
            Title number that was previously allocated to a property.
          example: AGL117262
        commonhold_type:
          oneOf:
          - $ref: '#/components/schemas/CommonholdType'
          x-force-type: CommonholdType
          x-data-quality:
          - tag: data_quality_commonhold_type_invalid
            message: The commonhold type is invalid.
        estate_interest:
          $ref: '#/components/schemas/EstateInterest'
        entries:
          $ref: '#/components/schemas/TitleEntries'
        properties:
          $ref: '#/components/schemas/TitleProperties'
        proprietors:
          $ref: '#/components/schemas/TitleProprietors'
      description: |
        Represents a title for land or property.
      example:
        title_number: AGL117262
        previous_title_number: AGL117262
        application_timestamp: 2000-01-23T04:56:07.000+00:00
        continuation_title_number: AGL117262
        caution_against_first_registration: true
        proprietors:
        - proprietor_type: proprietor_type
        - proprietor_type: proprietor_type
        pending_applications:
        - BADD31A
        - BADD31A
        welsh: false
        entries:
        - schedule:
            sequence: 1
            code: l
            header:
              eng: Schedule of rentcharges
              cym: Atodlen rhent-daliadau cofrestredig
          language_code: eng
          entry_text: No disposition by a sole proprietor of the registered estate
            (except a trust corporation) under which capital money arises is to be
            registered unless authorised by an order of the court.
          legacy_entry_id: '{}'
          sub_register_sequence: 1
          draft_entry_code: BX900
          role_code: OJPR
          priority_timestamp: 2000-01-23T04:56:07.000+00:00
          entry_sequence: 1
          draft_entry_version: 1
          sub_register_code: a
          entry_date: 2000-01-23
        - schedule:
            sequence: 1
            code: l
            header:
              eng: Schedule of rentcharges
              cym: Atodlen rhent-daliadau cofrestredig
          language_code: eng
          entry_text: No disposition by a sole proprietor of the registered estate
            (except a trust corporation) under which capital money arises is to be
            registered unless authorised by an order of the court.
          legacy_entry_id: '{}'
          sub_register_sequence: 1
          draft_entry_code: BX900
          role_code: OJPR
          priority_timestamp: 2000-01-23T04:56:07.000+00:00
          entry_sequence: 1
          draft_entry_version: 1
          sub_register_code: a
          entry_date: 2000-01-23
        edition_date: 2000-01-23
        estate_interest: estate_in_land
        tenure: freehold
        class_of_title: absolute
        properties:
        - sequence: 1
          address:
            description: 123 Smith Street, Plymouth (PL1 2AB)
            legacy_addr_id: 2019-11-18 12.52.12.555232
            type: uk
        - sequence: 1
          address:
            description: 123 Smith Street, Plymouth (PL1 2AB)
            legacy_addr_id: 2019-11-18 12.52.12.555232
            type: uk
        status:
          date: 2000-01-23
          value: open
        commonhold_type: ""
    TitleNumber:
      maxLength: 9
      type: string
      description: The unique reference number that refers to this title.
      example: AGL117262
    TitleStatus:
      type: string
      description: |
        The status of a title represents whether or not it has been superseded.
        An open title is one which is still in effect, whereas a closed title is no longer legally binding.
      example: open
      enum:
      - open
      - closed
    TitleStatusInfo:
      required:
      - value
      type: object
      properties:
        value:
          $ref: '#/components/schemas/TitleStatus'
        date:
          type: string
          description: |
            The date that the status of the title was changed.
          format: date
      description: |
        Encapsulates information related to the status of the title.
      example:
        date: 2000-01-23
        value: open
    TitleEntries:
      type: array
      description: The list of current entries on the register for this title.
      items:
        $ref: '#/components/schemas/RegisterEntry'
      x-data-quality:
      - tag: data_quality_schedule_code_invalid
        message: Ordering of entries failed due to an invalid schedule code.
    TitleProperties:
      type: array
      description: |
        The list of properties relating to this title.
        If there are multiple properties on the title, the property from the A1 entry appears first (if present),
        followed in order by those in the schedule.
      items:
        $ref: '#/components/schemas/Property'
    TitleProprietors:
      type: array
      description: The ordered list of proprietors relating to this title.
      items:
        $ref: '#/components/schemas/Proprietor'
    TopicId:
      type: string
      description: The unique identifier for the title's topic. This allows the requestor
        to subscribe to any changes on the title.
      example: arn:aws:sns:us-west-2:123456789012:my-topic
    TransferRequest:
      required:
      - application_type
      type: object
      properties:
        application_type:
          type: string
          enum:
          - transfer_of_whole
        additional_provisions:
          type: array
          description: any required or permitted statement, certificate or application
            and any agreed covenants, declarations and so on.
          items:
            oneOf:
            - type: string
            - type: number
            - type: integer
            - type: boolean
            - type: array
            - type: object
        consideration:
          $ref: '#/components/schemas/TransferRequest_consideration'
        declaration_of_trust:
          $ref: '#/components/schemas/DeclarationOfTrust'
        execution:
          $ref: '#/components/schemas/Execution'
        guarantee:
          $ref: '#/components/schemas/TransferRequest_guarantee'
        transfer_date:
          type: string
          description: The date on which the entry was added to the register.
          format: date
        transferrees:
          type: array
          items:
            $ref: '#/components/schemas/Proprietor'
        transferrors:
          type: array
          items:
            oneOf:
            - $ref: '#/components/schemas/PrivateIndividual'
            - $ref: '#/components/schemas/Organisation'
            - required:
              - notice_of_death
              - trustee
              type: object
              properties:
                notice_of_death:
                  $ref: '#/components/schemas/NoticeOfDeath'
                trustee:
                  $ref: '#/components/schemas/PrivateIndividual'
        sdlt_transaction_ref:
          type: string
          description: The HMRC-provided transaction reference for the completed SDLT
            payment
          example: ABCD1234
        consent_to_discharge:
          type: boolean
          description: Assurance that the lender has consented to remove the charge
      description: A request to draft a new application to update the register.
      allOf:
      - $ref: '#/components/schemas/ApplicationRequest'
    ValidationIssue:
      required:
      - issue_code
      - message
      - property_name
      type: object
      properties:
        issue_code:
          type: string
          description: A code identifying the type of issue that occurred. This allows
            integrating APIs to try to resolve the issue automatically.
        message:
          type: string
          description: A message summarising why this property failed to validate.
          example: A title does not exist for the given title number
        property_name:
          type: string
          description: The name of the property that this issue was raised for.
          example: title_number
        value:
          description: The value of the property that passed validation.
          example: AGL117262
          oneOf:
          - type: string
          - type: number
          - type: integer
          - type: boolean
          - type: array
          - type: object
      description: |
        Represents a single issue encountered while validating a property on a request body.
      example:
        issue_code: issue_code
        message: A title does not exist for the given title number
        value: AGL117262
        property_name: title_number
    ValidationSuccess:
      required:
      - property_name
      type: object
      properties:
        property_name:
          type: string
          description: The name of the property that passed validation.
          example: title_number
        value:
          description: The value of the property that passed validation.
          example: AGL117262
          oneOf:
          - type: string
          - type: number
          - type: integer
          - type: boolean
          - type: array
          - type: object
      description: |
        Represents a single property that passed validation on a request body.
      example:
        value: AGL117262
        property_name: title_number
    ValidationErrorResponse:
      required:
      - error_message
      - status
      type: object
      properties:
        status:
          maximum: 599
          minimum: 400
          type: integer
          description: The HTTP status code returned by the server with this response.
          format: int32
        error_message:
          type: string
          description: A human-readable message that provides a summary of the cause
            of the error.
        title:
          $ref: '#/components/schemas/Title'
        applications:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationRequestResponse'
      description: "Returned when a request body contains invalid property values.\n\
        \    \n"
    ValidationSuccessResponse:
      required:
      - status
      - title
      type: object
      properties:
        status:
          maximum: 202
          minimum: 200
          type: integer
          description: The HTTP status code returned by the server with this response.
          format: int32
        title:
          $ref: '#/components/schemas/Title'
        applications:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationRequestResponse'
      description: |
        Returned when a request body contains valid property values.
      example:
        title:
          title_number: AGL117262
          previous_title_number: AGL117262
          application_timestamp: 2000-01-23T04:56:07.000+00:00
          continuation_title_number: AGL117262
          caution_against_first_registration: true
          proprietors:
          - proprietor_type: proprietor_type
          - proprietor_type: proprietor_type
          pending_applications:
          - BADD31A
          - BADD31A
          welsh: false
          entries:
          - schedule:
              sequence: 1
              code: l
              header:
                eng: Schedule of rentcharges
                cym: Atodlen rhent-daliadau cofrestredig
            language_code: eng
            entry_text: No disposition by a sole proprietor of the registered estate
              (except a trust corporation) under which capital money arises is to
              be registered unless authorised by an order of the court.
            legacy_entry_id: '{}'
            sub_register_sequence: 1
            draft_entry_code: BX900
            role_code: OJPR
            priority_timestamp: 2000-01-23T04:56:07.000+00:00
            entry_sequence: 1
            draft_entry_version: 1
            sub_register_code: a
            entry_date: 2000-01-23
          - schedule:
              sequence: 1
              code: l
              header:
                eng: Schedule of rentcharges
                cym: Atodlen rhent-daliadau cofrestredig
            language_code: eng
            entry_text: No disposition by a sole proprietor of the registered estate
              (except a trust corporation) under which capital money arises is to
              be registered unless authorised by an order of the court.
            legacy_entry_id: '{}'
            sub_register_sequence: 1
            draft_entry_code: BX900
            role_code: OJPR
            priority_timestamp: 2000-01-23T04:56:07.000+00:00
            entry_sequence: 1
            draft_entry_version: 1
            sub_register_code: a
            entry_date: 2000-01-23
          edition_date: 2000-01-23
          estate_interest: estate_in_land
          tenure: freehold
          class_of_title: absolute
          properties:
          - sequence: 1
            address:
              description: 123 Smith Street, Plymouth (PL1 2AB)
              legacy_addr_id: 2019-11-18 12.52.12.555232
              type: uk
          - sequence: 1
            address:
              description: 123 Smith Street, Plymouth (PL1 2AB)
              legacy_addr_id: 2019-11-18 12.52.12.555232
              type: uk
          status:
            date: 2000-01-23
            value: open
          commonhold_type: ""
        status: 200
        applications:
        - application_type: transfer_of_whole
          validation_successes:
          - value: AGL117262
            property_name: title_number
          - value: AGL117262
            property_name: title_number
          validation_issues:
          - issue_code: issue_code
            message: A title does not exist for the given title number
            value: AGL117262
            property_name: title_number
          - issue_code: issue_code
            message: A title does not exist for the given title number
            value: AGL117262
            property_name: title_number
        - application_type: transfer_of_whole
          validation_successes:
          - value: AGL117262
            property_name: title_number
          - value: AGL117262
            property_name: title_number
          validation_issues:
          - issue_code: issue_code
            message: A title does not exist for the given title number
            value: AGL117262
            property_name: title_number
          - issue_code: issue_code
            message: A title does not exist for the given title number
            value: AGL117262
            property_name: title_number
    inline_response_201:
      allOf:
      - $ref: '#/components/schemas/ValidationSuccessResponse'
      - type: object
        properties:
          topic_id:
            $ref: '#/components/schemas/TopicId'
    ChargeRequest_title_guarantee:
      required:
      - guarantee_type
      type: object
      properties:
        guarantee_type:
          type: string
          enum:
          - full_title_guarantee
          - limited_title_guarantee
        modifications:
          type: string
    TransferRequest_consideration:
      required:
      - consideration_type
      type: object
      properties:
        consideration_type:
          type: string
          enum:
          - transfer_for_value
          - transfer_not_for_value
          - other_receipt
        currency:
          type: string
          enum:
          - gbp
          - eur
        amount:
          type: integer
          format: int32
          example: 150000
        other_receipt:
          type: string
    TransferRequest_guarantee:
      required:
      - guarantee_type
      type: object
      properties:
        guarantee_type:
          type: string
          enum:
          - full_title_guarantee
          - limited_title_guarantee
        modifications:
          type: string
          description: Any modifications on the title guarantee.
      description: The type of guarantee provided by the transferor(s)

